//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Green.Resource {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralTextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralTextResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Green.Resource.GeneralTextResource", typeof(GeneralTextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Voltando ao início....
        /// </summary>
        internal static string AlertReturnScreenStart {
            get {
                return ResourceManager.GetString("AlertReturnScreenStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário e/ou senha estão incorretos..
        /// </summary>
        internal static string ErrorInvalidLoginUserOrPassword {
            get {
                return ResourceManager.GetString("ErrorInvalidLoginUserOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Opção inválida..
        /// </summary>
        internal static string ErrorInvalidOption {
            get {
                return ResourceManager.GetString("ErrorInvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário ou/e Senha com caracteres especiais.
        /// </summary>
        internal static string ErrorLoginWithSpecialCharacter {
            get {
                return ResourceManager.GetString("ErrorLoginWithSpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha não foi confirmada..
        /// </summary>
        internal static string ErrorUnconfirmedPassword {
            get {
                return ResourceManager.GetString("ErrorUnconfirmedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fechar.
        /// </summary>
        internal static string ScreenTitleClose {
            get {
                return ResourceManager.GetString("ScreenTitleClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entrar.
        /// </summary>
        internal static string ScreenTitleLogin {
            get {
                return ResourceManager.GetString("ScreenTitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seleção de Jogo.
        /// </summary>
        internal static string ScreenTitleMenuGames {
            get {
                return ResourceManager.GetString("ScreenTitleMenuGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Início.
        /// </summary>
        internal static string ScreenTitleStart {
            get {
                return ResourceManager.GetString("ScreenTitleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Usuário.
        /// </summary>
        internal static string ScreenTitleUserCreate {
            get {
                return ResourceManager.GetString("ScreenTitleUserCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} regristrado.
        /// </summary>
        internal static string SucessRegisteredUser {
            get {
                return ResourceManager.GetString("SucessRegisteredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Boa sorte, até a próxima!.
        /// </summary>
        internal static string SucessThanksAccess {
            get {
                return ResourceManager.GetString("SucessThanksAccess", resourceCulture);
            }
        }
    }
}
